"""`pmex-shadow compose generate` — bots/*.yaml -> docker-compose.bots.yml. Adding a
bot is dropping a YAML file and regenerating (design doc §7); never hand-edit the
generated file.
"""

from __future__ import annotations

from pathlib import Path

import yaml

from pmex_shadow.config import BotConfig

HEADER = "# GENERATED by `pmex-shadow compose generate` from bots/*.yaml — do not hand-edit.\n"


def generate_compose(bots: list[BotConfig]) -> str:
    services = {}
    for bot in bots:
        services[f"bot-{bot.name}"] = {
            "build": ".",
            "depends_on": ["watcher"],
            "env_file": [".env", f"secrets/{bot.name}.env"],
            "volumes": [f"./bots/{bot.name}.yaml:/app/bots/{bot.name}.yaml:ro"],
            "command": ["bot", "run", bot.name],
            "stop_grace_period": "30s",  # must exceed the cancel-all path's worst case (FR-EXE-6)
            "restart": "unless-stopped",
        }
    doc = {"services": services}
    return HEADER + yaml.safe_dump(doc, sort_keys=False, default_flow_style=False)


def compute_overlaps(bots: list[BotConfig]) -> list[dict]:
    """FR-O-7: pairs of bots sharing targets with intersecting selectors, and their
    combined exposure — "bot2 overlaps sports_bot1 on 3 targets with identical
    selectors; combined exposure will be 2x" (design doc §2.2). Selectors are
    considered to intersect if either has no category constraint (matches
    everything) or their category sets share at least one entry — a coarse but
    honest approximation; the exact selector-composition logic lives in decide().
    """
    overlaps = []
    for i, a in enumerate(bots):
        for b in bots[i + 1:]:
            shared_targets = set(a.targets) & set(b.targets)
            if not shared_targets:
                continue
            a_cats = set(a.selectors.categories) if a.selectors.categories else None
            b_cats = set(b.selectors.categories) if b.selectors.categories else None
            selectors_intersect = a_cats is None or b_cats is None or bool(a_cats & b_cats)
            if not selectors_intersect:
                continue
            overlaps.append({
                "bot_a": a.name, "bot_b": b.name, "shared_targets": sorted(shared_targets),
                "combined_exposure_usd": a.risk.envelope_usd + b.risk.envelope_usd,
            })
    return overlaps


def load_all_bots(bots_dir: Path) -> list[BotConfig]:
    from pmex_shadow.config import load_bot_config

    bots = []
    for path in sorted(bots_dir.glob("*.yaml")):
        try:
            bots.append(load_bot_config(path))
        except Exception:
            continue
    return bots
